# Generated by Django 4.1.1 on 2022-12-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_paymentmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmaster',
            name='balance',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterModelTable(
            name='paymentmaster',
            table='Payment Master',
        ),
    ]
